### ISSUE TITLE
Spelling underline when composing SMS?

### ISSUE THREAD

**Issue by bhendel-zz** [jlippold/WifiSMS#18]
So far this looks like it is EXACTLY what I am looking for! Too bad this kind of thing isn't allowed on the app store. And it was free? Crazy. Nice job!

Only problem so far is that FireFox won't underline spelling errors in the compose text field. I was previously using NotifyPro, which used growl on the PC and opened up a really basic php page hosted on the phone with a text area for composition, and FF would underline my spelling mistakes.

This is not happening in WiFiSMS. Since you are simply using a text field, is it possible that your CSS is somehow preventing FF underlines from showing. Anyone else experiencing this?

Question, is it just me, or does locking the phone with the web client running not shut down the WiFi radio after 5 mins? I've locked my phone and had a continuous ping running for over 10 minutes and it hasn't disconnected.

Wicked app so far! I will definitely Donate via PayPal for continued development.

-Brian

**Comment by jasonchutko** [comment]
If the phone is plugged into a power source, the radio stays on for a while longer.

Spelling correction is confirmed working on Chrome out of the box.

I just tried it in Firefox, didn't work.  Then I installed a language package, and the spellcheck worked.

Have you installed a language pack?  Otherwise it might be the fact that Firefox only spellchecks for multiline text areas, so you have to enable a config option to check ALL text fields.

-Jason.

**Comment by bhendel-zz** [comment]
Worked!  Thank you!  This is perfect.  I followed.

http://www.nirmaltv.com/2008/03/08/how-to-enable-spell-check-in-text-fields-in-firefox/

-Brian

**Comment by jasonchutko** [comment]
Enjoy!

**Comment by treason** [comment]
There's an about:config setting in FF to allow text input spell check. Thats what I do.
